name: Deploy to Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Server
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SSH_HOST }}
                  port: ${{ secrets.SSH_PORT }} # Port SSH kustom Anda
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      cd /var/www/api-wowborneo
                      git pull origin main
                      npm install
                      npm run build  
                      npx dotenv -e .env.production -- prisma generate
                      npx dotenv -e .env.production -- prisma migrate deploy
                      pm2 restart ecosystem.config.cjs
